WITH
-- CTE 1: Gera uma série de meses para o relatório
MESES_RELATORIO AS (
    SELECT
        ADD_MONTHS(TRUNC(TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'MM'), level - 1) AS PRIMEIRO_DIA_MES
    FROM
        DUAL
    CONNECT BY
        ADD_MONTHS(TRUNC(TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'MM'), level - 1) <= LAST_DAY(ADD_MONTHS(SYSDATE, -1))
),

-- CTE 2: Unifica as contas contábeis dos parceiros
PARCEIRO_CONTAS AS (
    SELECT CODPARC, NOMEPARC, CODCTACTB AS CONTA_CONTABIL FROM TGFPAR WHERE CODCTACTB IS NOT NULL
    UNION
    SELECT CODPARC, NOMEPARC, CODCTACTB2 AS CONTA_CONTABIL FROM TGFPAR WHERE CODCTACTB2 IS NOT NULL
),

-- CTE 3: Identifica contas pai - apenas um nível acima
CONTAS_PAI AS (
    SELECT DISTINCT
        p.CODCTACTB,
        p.CTACTB,
        -- Extrai apenas um nível pai: remove o último segmento e adiciona '0000'
        CASE 
            WHEN REGEXP_COUNT(p.CTACTB, '\.') >= 1 
            THEN REGEXP_REPLACE(p.CTACTB, '\.[0-9]+$', '.0000')
            ELSE NULL
        END AS CONTA_PAI
    FROM TCBPLA p
    WHERE EXISTS (
        SELECT 1 FROM PARCEIRO_CONTAS pc WHERE pc.CONTA_CONTABIL = p.CODCTACTB
    )
    AND p.CTACTB NOT LIKE '%.0000'
),

-- CTE 4: Busca informações das contas pai
INFO_CONTAS_PAI AS (
    SELECT 
        cp.CODCTACTB AS CONTA_FILHA,
        cp.CTACTB AS CONTA_FILHA_COMPLETA,
        pp.CODCTACTB AS CONTA_PAI_COD,
        pp.CTACTB AS CONTA_PAI_COMPLETA,
        pp.DESCRCTA AS CONTA_PAI_DESCRICAO
    FROM CONTAS_PAI cp
    INNER JOIN TCBPLA pp ON pp.CTACTB = cp.CONTA_PAI
    WHERE cp.CONTA_PAI IS NOT NULL
),

-- CTE 5: Calcula o Saldo do Módulo Financeiro (original)
SALDO_FINANCEIRO AS (
    SELECT
        p.CONTA_CONTABIL,
        PL.CTACTB AS CONTA_COMPLETA,
        p.CODPARC,
        p.NOMEPARC,
        EXTRACT(YEAR FROM mr.PRIMEIRO_DIA_MES) AS ANO,
        EXTRACT(MONTH FROM mr.PRIMEIRO_DIA_MES) AS MES,
        COALESCE(SUM(f.VLRDESDOB * f.RECDESP), 0) AS SALDO_FINANCEIRO
    FROM
        (SELECT DISTINCT CODPARC FROM TGFFIN WHERE DTENTSAI >= TO_DATE('2025-01-01', 'YYYY-MM-DD') AND CODEMP = 1) parceiros
        CROSS JOIN MESES_RELATORIO mr
        INNER JOIN PARCEIRO_CONTAS p ON p.CODPARC = parceiros.CODPARC
        JOIN TCBPLA PL ON PL.CODCTACTB = p.CONTA_CONTABIL
        LEFT JOIN TGFFIN f ON f.CODPARC = parceiros.CODPARC
                           AND f.PROVISAO = 'N'
                           AND f.DTENTSAI <= LAST_DAY(mr.PRIMEIRO_DIA_MES)
                           AND (f.DHBAIXA > LAST_DAY(mr.PRIMEIRO_DIA_MES) OR f.DHBAIXA IS NULL)
    GROUP BY
        p.CONTA_CONTABIL,
        PL.CTACTB,
        p.CODPARC,
        p.NOMEPARC,
        mr.PRIMEIRO_DIA_MES
),

-- CTE 6: Calcula o Saldo do Módulo Contábil (original)
SALDO_CONTABIL AS (
    SELECT
        S.CODCTACTB as CONTA_CONTABIL,
        PL.CTACTB AS CONTA_COMPLETA,
        PC.CODPARC,
        PC.NOMEPARC,
        EXTRACT(YEAR FROM S.REFERENCIA) AS ANO,
        EXTRACT(MONTH FROM S.REFERENCIA) AS MES,
        (SALDOINICMES+DEBMES-CREDMES) AS SALDO_CONTABIL
    FROM
        PARCEIRO_CONTAS PC
    JOIN TCBPLA PL ON PL.CODCTACTB = PC.CONTA_CONTABIL
    JOIN TCBSAL S ON (S.CODCTACTB = PL.CODCTACTB) AND (S.CODEMP = PL.CODEMP) 
    WHERE S.REFERENCIA >= TO_DATE('2025-01-01', 'YYYY-MM-DD') AND S.REFERENCIA <= SYSDATE AND S.CODEMP = 1

),

-- CTE 7: Saldos das contas pai - Financeiro (agrupado por conta pai apenas)
SALDO_FINANCEIRO_PAI AS (
    SELECT
        icp.CONTA_PAI_COD AS CONTA_CONTABIL,
        icp.CONTA_PAI_COMPLETA AS CONTA_COMPLETA,
        icp.CONTA_PAI_DESCRICAO AS NOME_CONTA_PAI,
        sf.ANO,
        sf.MES,
        SUM(sf.SALDO_FINANCEIRO) AS SALDO_FINANCEIRO
    FROM SALDO_FINANCEIRO sf
    INNER JOIN INFO_CONTAS_PAI icp ON icp.CONTA_FILHA = sf.CONTA_CONTABIL
    GROUP BY
        icp.CONTA_PAI_COD,
        icp.CONTA_PAI_COMPLETA,
        icp.CONTA_PAI_DESCRICAO,
        sf.ANO,
        sf.MES
),

-- CTE 8: Saldos das contas pai - Contábil (agrupado por conta pai apenas)
SALDO_CONTABIL_PAI AS (
    SELECT
        icp.CONTA_PAI_COD AS CONTA_CONTABIL,
        icp.CONTA_PAI_COMPLETA AS CONTA_COMPLETA,
        icp.CONTA_PAI_DESCRICAO AS NOME_CONTA_PAI,
        sc.ANO,
        sc.MES,
        SUM(sc.SALDO_CONTABIL) AS SALDO_CONTABIL
    FROM SALDO_CONTABIL sc
    INNER JOIN INFO_CONTAS_PAI icp ON icp.CONTA_FILHA = sc.CONTA_CONTABIL
    GROUP BY
        icp.CONTA_PAI_COD,
        icp.CONTA_PAI_COMPLETA,
        icp.CONTA_PAI_DESCRICAO,
        sc.ANO,
        sc.MES
),

-- CTE 9: União de todos os saldos (filhas + pais)
TODOS_SALDOS AS (
    -- Saldos das contas filhas
    SELECT
        COALESCE(FIN.CODPARC, CTB.CODPARC) AS CODPARC,
        COALESCE(FIN.NOMEPARC, CTB.NOMEPARC) AS NOMEPARC,
        COALESCE(FIN.CONTA_CONTABIL, CTB.CONTA_CONTABIL) AS CONTA_CONTABIL,
        COALESCE(FIN.CONTA_COMPLETA, CTB.CONTA_COMPLETA) AS CONTA_COMPLETA,
        COALESCE(FIN.ANO, CTB.ANO) AS ANO,
        COALESCE(FIN.MES, CTB.MES) AS MES,
        COALESCE(FIN.SALDO_FINANCEIRO, 0) AS SALDO_FINANCEIRO,
        COALESCE(CTB.SALDO_CONTABIL, 0) AS SALDO_CONTABIL,
        (COALESCE(FIN.SALDO_FINANCEIRO, 0) - COALESCE(CTB.SALDO_CONTABIL, 0)) AS DIFERENCA,
        'FILHA' AS TIPO_CONTA
    FROM
        SALDO_FINANCEIRO FIN
    FULL OUTER JOIN
        SALDO_CONTABIL CTB ON FIN.CODPARC = CTB.CODPARC AND FIN.ANO = CTB.ANO AND FIN.MES = CTB.MES

    UNION ALL

    -- Saldos das contas pai
    SELECT
        NULL AS CODPARC, -- Conta pai não tem parceiro específico
        COALESCE(FINP.NOME_CONTA_PAI, CTBP.NOME_CONTA_PAI) AS NOMEPARC, -- Nome da conta pai
        COALESCE(FINP.CONTA_CONTABIL, CTBP.CONTA_CONTABIL) AS CONTA_CONTABIL,
        COALESCE(FINP.CONTA_COMPLETA, CTBP.CONTA_COMPLETA) AS CONTA_COMPLETA,
        COALESCE(FINP.ANO, CTBP.ANO) AS ANO,
        COALESCE(FINP.MES, CTBP.MES) AS MES,
        COALESCE(FINP.SALDO_FINANCEIRO, 0) AS SALDO_FINANCEIRO,
        COALESCE(CTBP.SALDO_CONTABIL, 0) AS SALDO_CONTABIL,
        (COALESCE(FINP.SALDO_FINANCEIRO, 0) - COALESCE(CTBP.SALDO_CONTABIL, 0)) AS DIFERENCA,
        'PAI' AS TIPO_CONTA
    FROM
        SALDO_FINANCEIRO_PAI FINP
    FULL OUTER JOIN
        SALDO_CONTABIL_PAI CTBP ON FINP.CONTA_CONTABIL = CTBP.CONTA_CONTABIL
                                AND FINP.ANO = CTBP.ANO 
                                AND FINP.MES = CTBP.MES
)

-- Consulta Final: Comparação dos saldos (filhas + pais)
SELECT
    CODPARC,
    NOMEPARC,
    CONTA_CONTABIL,
    CONTA_COMPLETA,
    ANO,
    MES,
    SALDO_FINANCEIRO,
    SALDO_CONTABIL,
    DIFERENCA,
    TIPO_CONTA
FROM TODOS_SALDOS
WHERE
    -- Filtra para mostrar apenas onde há diferença
    (DIFERENCA < -0.2 OR DIFERENCA > 0.2)
    --and CODPARC = 5276
    AND MES = NVL(:MES, MES)
ORDER BY
    CONTA_COMPLETA, 
    TIPO_CONTA DESC, -- PAI aparece antes de FILHA
    NOMEPARC, 
    ANO, 
    MES